const { startProcess }            = require('./startProcess.js'),
      { getTime }                 = require('./getTime'),
      { asyncFunc }               = require('./asyncFunc'),
      { checkAccess }             = require('./checkAccess'),
      { checkFileInfo }           = require('./checkFileInfo'),
      { checkParams }             = require('./checkParams'),
      { createOrUpdateModel }     = require('./createOrUpdateModel'),
      { formatFilename }          = require('./formatFilename'),
      { generateDirMap }          = require('./generateDirMap'),
      { makeCrypto }              = require('./makeCrypto'),
      { readDir }                 = require('./readDir'),
      { transferNum }             = require('./transferNum'),
      { trimTxt }                 = require('./trimTxt'),
      { updateModelAndReturnRet } = require('./updateModelAndReturnRet'),
      { removeModelHrefs }        = require('./removeModelHrefs'),
      { CacheStore }              = require('./CacheStore'),
      { addErrorArgs }            = require('./addErrorArgs'),
      { logger }                  = require('./logger')


module.exports = {
  startProcess,
  getTime,
  asyncFunc,
  checkAccess,
  checkFileInfo,
  checkParams,
  createOrUpdateModel,
  formatFilename,
  generateDirMap,
  makeCrypto,
  readDir,
  transferNum,
  trimTxt,
  updateModelAndReturnRet,
  removeModelHrefs,
  CacheStore,
  addErrorArgs,
  logger,
  MODELS: generateDirMap('models'),
  CRAWLERS: generateDirMap('crawler'),
}
